### ISSUE TITLE
ngModel return false

### ISSUE THREAD

**Issue by Dioude** [JoaoGuedes/ngDisposableMail#1]
Hi,

I was looking for your directive and I realised that the ng-model returns "false".

I tryied on your Plunker, just added {{user.email}} anywhere in the <form> to display the value, and it shows "false".

So we can't get the mail that we entered in the input.

**Comment by Dioude** [comment]
found a workaround,

replacing : 
`ngModel.$setValidity("disposable", true);
 return false;`

by 

`ngModel.$setValidity("disposable", true);
 return value;`

**Comment by JoaoGuedes** [comment]
Hi @Dioude,
That's correct, it was a bug on the code.
You should return the value always and not a boolean value.
